### ISSUE TITLE
ЦК ломается после гринтекста

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1130]
### Описание

Пропадают стены на цк после гринтекста, эвак был поломан. Админ отрапортовал, что тоже самое было когда он спавнил шаттл на мапе цк

### Шаги воспроизведения

1. Закончить раунд гринтекстом

2. Попытаться заспавнить шаттл на цк

### Скриншоты

![image](https://github.com/SerbiaStrong-220/space-station-14/assets/172140058/80eded30-204b-4bce-9874-3cc01d85bcbc)

**Comment by OwlMe1steR** [comment]
Была проведена следующая тестировка на картах Axioma, Nox, Frankenstein

1. Проверка ограничения гридов на СЦК.
2. Закончить раунд досрочно (гринтекст) на эвакуационном шаттле.
3. Окончить раунд (гринтекст) без происшествий на эвакуационном шаттле, но заблокировать возможность пристыковаться в назначенном месте.
4. Повредить эвакуационный шаттл и закончить раунд досрочно (гринтекст).
5. Повредить эвакуационный шаттл, но дождаться прилёта на СЦК.
6. Повредить саму СЦК, но не повреждать эвакуационный шаттл
7. Повредить СЦК и эвакуционный шаттл
8. Повторить опыт номер 7, но закончить раунд досрочно (гринтекст)

Все попытки реализовать данный баг увенчались неудачей.

Доп. комментарий:
Известен номер раунда 12690, который проходил на карте Frankenstein.
Ожидаем апдейт от Вера.

**Comment by gogenych** [comment]
```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.RecursiveMapUpdate(EntityUid uid, TransformComponent xform, PhysicsComponent body, PhysicsMapComponent newMap, PhysicsMapComponent oldMap) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 220
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.RecursiveMapUpdate(EntityUid uid, TransformComponent xform, PhysicsComponent body, PhysicsMapComponent newMap, PhysicsMapComponent oldMap) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 225
   at Robust.Shared.Physics.Systems.SharedPhysicsSystem.OnParentChange(Entity`2 ent, EntityUid oldParent, Nullable`1 oldMap) in RobustToolbox/Robust.Shared/Physics/Systems/SharedPhysicsSystem.cs:line 155
   at Robust.Shared.GameObjects.SharedTransformSystem.RaiseMoveEvent(Entity`2 ent, EntityUid oldParent, Vector2 oldPosition, Angle oldRotation, Nullable`1 oldMap) in RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.cs:line 281
   at Robust.Shared.GameObjects.SharedTransformSystem.SetCoordinates(Entity`2 entity, EntityCoordinates value, Nullable`1 rotation, Boolean unanchor, TransformComponent newParent, TransformComponent oldParent) in RobustToolbox/Robust.Shared/GameObjects/Systems/SharedTransformSystem.Component.cs:line 584
   at Content.Server.Shuttles.Systems.ShuttleSystem.FTLDock(Entity`1 shuttle, DockingConfig config) in Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs:line 681
   at Content.Server.Shuttles.Systems.ShuttleSystem.UpdateFTLArriving(Entity`2 entity) in Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs:line 479
   at Content.Server.Shuttles.Systems.ShuttleSystem.UpdateHyperspace() in Content.Server/Shuttles/Systems/ShuttleSystem.FasterThanLight.cs:line 565
   at Robust.Shared.GameObjects.EntitySystemManager.TickUpdate(Single frameTime, Boolean noPredictions) in RobustToolbox/Robust.Shared/GameObjects/EntitySystemManager.cs:line 306
```

ошибка поймана за попу, баг движка отправляется оффам
