### ISSUE TITLE
Дюп патронов на детективе

### ISSUE THREAD

**Issue by gogenych** [SerbiaStrong-220/space-station-14#1381]
### Описание

Каким-то образом детектив смог найти 100 патрон на револьвер открыв себя через ПКМ. Его одежда на скриншоте. Раса: человек. Воспроизвести на кукле не удалось, требуются качественные тесты. 

Патроны видно только с его точки зрения, у меня на агосте было всё окей

### Скриншоты

![image](https://github.com/user-attachments/assets/88a0fb1d-59f6-4e87-897c-e077a67a3742)
![image](https://github.com/user-attachments/assets/fbc7aaeb-2be0-4fcc-941a-27a7a0cd9c2f)

**Comment by OwlMe1steR** [comment]
Что ж, попробую описать, как это работает.

1. Для начала мы берём револьвер и разряжаем его. 
2. После этого разряжаем спидлоадер.
3. Затем вставляем меньше 6 патронов в револьвер. Если хотим, чтобы на нас осталось больше патронов, достаточно одного.
4. Заполняем спидлоадер патронами и пытаемся пополнить револьвер. Определённое количество патронов окажется у нас и выпадет одновременно, потому что по какой-то причине он не может полностью заполнить револьвер.
5. Поздравляем, Вы надюпали огромное кол-во патрон.

![Image](https://github.com/user-attachments/assets/250b580b-87a1-453e-8786-45e44f3dd522)



![Image](https://github.com/user-attachments/assets/3e4ea63f-59a8-4dc1-aae2-a593a1c62e46)

**Comment by gogenych** [comment]
Нужно больше данных, баг очевидно есть, но сложно поймать

**Comment by gogenych** [comment]
> Нужно больше данных, баг очевидно есть, но сложно поймать

не знаю почему я это написал, баг определенно есть и его нужно фиксить. @Ady4ik в закреп желательно

**Comment by SIXSEVENONE** [comment]
Ретест на **debug** билде из **master** ветки.
Попытка воспроизведения ишуи вызывает краш сервера.

**Шаги воспроизведения:**
1. Спавним Инспктор и спидлоадер .45
2. Разряжаем Инспектор
3. Заряжаем один патрон в Инспектор
4. Кликаем полным спидлоадером по револьверу

**Ожидаемый результат:**
5 из 6 патронов перенесены в револьвер, 1 патрон остался в спидлоадере или выпал на пол

**Фактический результат:**
Краш клиента и сервера по причине ошибки

**Текст ошибки:**
`[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.TryRevolverInsert(EntityUid revolverUid, RevolverAmmoProviderComponent component, EntityUid uid, Nullable`1 user) in C:\Users\671\ss14\space-station-14\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.Revolver.cs:line 160
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnRevolverInteractUsing(EntityUid uid, RevolverAmmoProviderComponent component, InteractUsingEvent args) in C:\Users\671\ss14\space-station-14\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.Revolver.cs:line 60
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass76_1.<EntCollectOrdered>b__0(Unit& ev) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 664
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 52
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 236
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 159
   at Content.Shared.Interaction.SharedInteractionSystem.InteractUsing(EntityUid user, EntityUid used, EntityUid target, EntityCoordinates clickLocation, Boolean checkCanInteract, Boolean checkCanUse) in C:\Users\671\ss14\space-station-14\Content.Shared\Interaction\SharedInteractionSystem.cs:line 1073
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryInteractHandWithActiveHand(EntityUid uid, String handName, HandsComponent handsComp) in C:\Users\671\ss14\space-station-14\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Interactions.cs:line 137
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.HandleInteractUsingInHand(RequestHandInteractUsingEvent msg, EntitySessionEventArgs args) in C:\Users\671\ss14\space-station-14\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Interactions.cs:line 72
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\671\ss14\space-station-14\Content.Server\Program.cs:line 9
Unhandled exception. Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
   at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.TryRevolverInsert(EntityUid revolverUid, RevolverAmmoProviderComponent component, EntityUid uid, Nullable`1 user) in C:\Users\671\ss14\space-station-14\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.Revolver.cs:line 160
   at Content.Shared.Weapons.Ranged.Systems.SharedGunSystem.OnRevolverInteractUsing(EntityUid uid, RevolverAmmoProviderComponent component, InteractUsingEvent args) in C:\Users\671\ss14\space-station-14\Content.Shared\Weapons\Ranged\Systems\SharedGunSystem.Revolver.cs:line 60
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass54_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 272
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass67_0`1.<EntSubscribe>b__0(EntityUid uid, IComponent comp, Unit& ev) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 460
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass76_1.<EntCollectOrdered>b__0(Unit& ev) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 664
   at Robust.Shared.GameObjects.EntityEventBus.DispatchOrderedEvents(Unit& eventArgs, ValueList`1& found) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 52
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalOrdered(EntityUid uid, Type eventType, EventData subs, Unit& unitRef, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Ordering.cs:line 43
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEventCore(EntityUid uid, Unit& unitRef, Type type, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 236
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.EntitySystem.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntitySystem.cs:line 159
   at Content.Shared.Interaction.SharedInteractionSystem.InteractUsing(EntityUid user, EntityUid used, EntityUid target, EntityCoordinates clickLocation, Boolean checkCanInteract, Boolean checkCanUse) in C:\Users\671\ss14\space-station-14\Content.Shared\Interaction\SharedInteractionSystem.cs:line 1073
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.TryInteractHandWithActiveHand(EntityUid uid, String handName, HandsComponent handsComp) in C:\Users\671\ss14\space-station-14\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Interactions.cs:line 137
   at Content.Shared.Hands.EntitySystems.SharedHandsSystem.HandleInteractUsingInHand(RequestHandInteractUsingEvent msg, EntitySessionEventArgs args) in C:\Users\671\ss14\space-station-14\Content.Shared\Hands\EntitySystems\SharedHandsSystem.Interactions.cs:line 72
   at Robust.Shared.GameObjects.EventBusExt.HandlerWrapper`1.Invoke(EntitySessionMessage`1 msg) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EventBusExt.cs:line 46
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass4_0`1.<SubscribeEvent>b__0(Unit& ev) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 173
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEventCore(EventSource source, Unit& unitRef, EventData subs) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 335
   at Robust.Shared.GameObjects.EntityEventBus.ProcessSingleEvent(EventSource source, Unit& unitRef, Type eventType) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.RaiseEvent(EventSource source, Object toRaise) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\GameObjects\EntityEventBus.Broadcast.cs:line 267
   at Robust.Server.GameObjects.ServerEntityManager.<Initialize>b__8_0(Object _, Object systemMsg) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 53
   at Robust.Server.GameObjects.ServerEntityManager.DispatchEntityNetworkMessage(MsgEntity message) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 266
   at Robust.Server.GameObjects.ServerEntityManager.TickUpdate(Single frameTime, Boolean noPredictions, Histogram histogram) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\GameObjects\ServerEntityManager.cs:line 192
   at Robust.Server.BaseServer.Update(FrameEventArgs frameEventArgs) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 731
   at Robust.Server.BaseServer.<SetupMainLoop>b__67_1(Object sender, FrameEventArgs args) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 544
   at Robust.Shared.Timing.GameLoop.Run() in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Shared\Timing\GameLoop.cs:line 235
   at Robust.Server.BaseServer.MainLoop() in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\BaseServer.cs:line 571
   at Robust.Server.Program.ParsedMain(CommandLineArgs args, Boolean contentStart, ServerOptions options) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 74
   at Robust.Server.Program.Start(String[] args, ServerOptions options, Boolean contentStart) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\Program.cs:line 42
   at Robust.Server.ContentStart.Start(String[] args) in C:\Users\671\ss14\space-station-14\RobustToolbox\Robust.Server\ContentStart.cs:line 10
   at Content.Server.Program.Main(String[] args) in C:\Users\671\ss14\space-station-14\Content.Server\Program.cs:line 9`

**Comment by SIXSEVENONE** [comment]
Ретест на билде v9DE66D6 от 10.03.2025

Баг не воспроизводится на текущей версии. Пофикшено, закрыто.
